version: "3.8"

services:
  # twitter-mysql:
  #   image: mysql
  #   container_name: twitter-mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: twitter_like
  #   volumes:
  #     - /home/yogadobo/Documents/Go/Projects/twitter-like/mysql/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql
  
  twitter:
    build: .
    image: twitte-like
    container_name: twitter
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}